import unittest

import amifind

class TestException(unittest.TestCase):
    def test_exception_message(self):
        self.assertTrue(True)
        
if __name__ == '__main__':
    unittest.main()
